[force-calculation]
    force_mode = 'FORCE_LIEN_TENSION'
    Ec = 




# Base force contributions
'FORCE_LINE_TENSION': {'Ec': Ec, 'Ecore_junc_fact': Ecore_junc_fact} # core + applied PK forces
'FORCE_CORE_SELF_PKEXT': {'Ec': Ec, 'Ecore_junc_fact': Ecore_junc_fact} # core + self + applied PK forces
'FORCE_COREMD_SELF_PKEXT': {'rc': rc, 'porder0': porder0, 'pcoeffs0': pcoeffs0, 'porder1': porder1, 'pcoeffs1': pcoeffs1} # spline core + self + applied PK forces
'FORCE_SEGSEG_ISO': {'cutoff': cutoff} # short-range forces
'FORCE_SEGSEG_ISO_FFT': {'cutoff': cutoff} # short-range forces with FFT correction
'FORCE_FFT': {'Ngrid': Ngrid} # long-range FFT force
'FORCE_LONG_FFT_SHORT_ISO': {'Ngrid': Ngrid} # short-range forces with FFT correction + long-range FFT force
'FORCE_N2_ISO': {} # brute-force N2 force
# Composite force models
'LINE_TENSION_MODEL': {'Ec': Ec, 'Ecore_junc_fact': Ecore_junc_fact} # core + applied PK forces, same as FORCE_LINE_TENSION
'CUTOFF_MODEL': {'cutoff': cutoff, 'Ec': Ec, 'Ecore_junc_fact': Ecore_junc_fact} # core + self + applied PK + short-range forces, same as FORCE_CORE_SELF_PKEXT + FORCE_SEGSEG_ISO
'DDD_FFT_MODEL': {'Ngrid': Ngrid, 'Ec': Ec, 'Ecore_junc_fact': Ecore_junc_fact} # core + self + applied PK + short-range FFT + longe-range FFT forces, same as FORCE_CORE_SELF_PKEXT + FORCE_LONG_FFT_SHORT_ISO
'SUBCYCLING_MODEL': {'Ngrid': Ngrid, 'Ec': Ec, 'Ecore_junc_fact': Ecore_junc_fact} # core + self + applied PK + short-range FFT + longe-range FFT forces